# coding: utf-8

"""
3Di API

3Di simulation API (latest stable version: v3)   Framework release: 3.4.71   3Di core release: 3.6.10  deployed on:  09:22AM (UTC) on September 01, 2025

The version of the OpenAPI document: v3
Contact: info@nelen-schuurmans.nl
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing_extensions import Self


class CreateThreedimodel(BaseModel):
    """
    CreateThreedimodel
    """  # noqa: E501

    inherit_from_previous_threedimodel: Optional[StrictBool] = Field(
        default=True,
        description="Try to inherit simulation templates from previous threedimodel (in case of regenerate)",
    )
    inherit_from_previous_revision: Optional[StrictBool] = Field(
        default=False,
        description="Try to inherit simulation templates from previous revision",
    )
    __properties: ClassVar[List[str]] = [
        "inherit_from_previous_threedimodel",
        "inherit_from_previous_revision",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateThreedimodel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateThreedimodel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "inherit_from_previous_threedimodel": obj.get(
                    "inherit_from_previous_threedimodel"
                )
                if obj.get("inherit_from_previous_threedimodel") is not None
                else True,
                "inherit_from_previous_revision": obj.get(
                    "inherit_from_previous_revision"
                )
                if obj.get("inherit_from_previous_revision") is not None
                else False,
            }
        )
        return _obj
