# coding: utf-8

"""
3Di API

3Di simulation API (latest stable version: v3)   Framework release: 3.4.71   3Di core release: 3.6.10  deployed on:  09:22AM (UTC) on September 01, 2025

The version of the OpenAPI document: v3
Contact: info@nelen-schuurmans.nl
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set, Union

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing_extensions import Annotated, Self


class FileMeta(BaseModel):
    """
    FileMeta
    """  # noqa: E501

    values_reference: Optional[
        Annotated[str, Field(min_length=1, strict=True, max_length=255)]
    ] = None
    units: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=64)]] = (
        None
    )
    timestamps: Optional[List[Annotated[int, Field(strict=True, ge=0)]]] = Field(
        default=None, description="seconds in the simulation"
    )
    offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(
        default=None, description="seconds in the simulation"
    )
    duration: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(
        default=None, description="seconds"
    )
    geotransform: Optional[List[Union[StrictFloat, StrictInt]]] = None
    epsg_code: Optional[StrictInt] = None
    interval: Optional[StrictInt] = None
    error: Optional[
        Annotated[str, Field(min_length=1, strict=True, max_length=512)]
    ] = None
    fill_value: Optional[
        Annotated[str, Field(min_length=1, strict=True, max_length=128)]
    ] = None
    __properties: ClassVar[List[str]] = [
        "values_reference",
        "units",
        "timestamps",
        "offset",
        "duration",
        "geotransform",
        "epsg_code",
        "interval",
        "error",
        "fill_value",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FileMeta from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FileMeta from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "values_reference": obj.get("values_reference"),
                "units": obj.get("units"),
                "timestamps": obj.get("timestamps"),
                "offset": obj.get("offset"),
                "duration": obj.get("duration"),
                "geotransform": obj.get("geotransform"),
                "epsg_code": obj.get("epsg_code"),
                "interval": obj.get("interval"),
                "error": obj.get("error"),
                "fill_value": obj.get("fill_value"),
            }
        )
        return _obj
