# coding: utf-8

"""
3Di API

3Di simulation API (latest stable version: v3)   Framework release: 3.4.71   3Di core release: 3.6.10  deployed on:  09:22AM (UTC) on September 01, 2025

The version of the OpenAPI document: v3
Contact: info@nelen-schuurmans.nl
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set, Union

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing_extensions import Annotated, Self

from ..models.polygon import Polygon


class ForcingSubstanceWithZone(BaseModel):
    """
    ForcingSubstanceWithZone
    """  # noqa: E501

    id: Optional[StrictInt] = None
    substance: StrictStr
    substance_id: Optional[StrictInt] = None
    substance_name: Optional[StrictStr] = None
    concentrations: Annotated[
        List[
            Annotated[
                List[Union[StrictFloat, StrictInt]], Field(min_length=2, max_length=2)
            ]
        ],
        Field(min_length=1, max_length=300),
    ] = Field(
        description="Timeseries provided as a nested list. The inner list consists of exactly 2 values: timestamp, value"
    )
    zone: Optional[Polygon] = None
    __properties: ClassVar[List[str]] = [
        "id",
        "substance",
        "substance_id",
        "substance_name",
        "concentrations",
        "zone",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ForcingSubstanceWithZone from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set(
            [
                "id",
                "substance_id",
                "substance_name",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of zone
        if self.zone:
            _dict["zone"] = self.zone.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ForcingSubstanceWithZone from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "substance": obj.get("substance"),
                "substance_id": obj.get("substance_id"),
                "substance_name": obj.get("substance_name"),
                "concentrations": obj.get("concentrations"),
                "zone": Polygon.from_dict(obj["zone"])
                if obj.get("zone") is not None
                else None,
            }
        )
        return _obj
