# coding: utf-8

"""
3Di API

3Di simulation API (latest stable version: v3)   Framework release: 3.4.71   3Di core release: 3.6.10  deployed on:  09:22AM (UTC) on September 01, 2025

The version of the OpenAPI document: v3
Contact: info@nelen-schuurmans.nl
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set
from uuid import UUID

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr, field_validator
from typing_extensions import Self


class GroundWaterSubstanceConcentration(BaseModel):
    """
    GroundWaterSubstanceConcentration
    """  # noqa: E501

    url: Optional[StrictStr] = None
    simulation: Optional[StrictStr] = None
    substance: StrictStr
    substance_id: Optional[StrictInt] = None
    substance_name: Optional[StrictStr] = None
    initial_concentration: StrictStr
    initial_concentration_id: Optional[StrictInt] = None
    uid: Optional[UUID] = None
    id: Optional[StrictInt] = None
    aggregation_method: StrictStr
    __properties: ClassVar[List[str]] = [
        "url",
        "simulation",
        "substance",
        "substance_id",
        "substance_name",
        "initial_concentration",
        "initial_concentration_id",
        "uid",
        "id",
        "aggregation_method",
    ]

    @field_validator("aggregation_method")
    def aggregation_method_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(["mean", "max", "min"]):
            raise ValueError("must be one of enum values ('mean', 'max', 'min')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GroundWaterSubstanceConcentration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set(
            [
                "url",
                "simulation",
                "substance_id",
                "substance_name",
                "initial_concentration_id",
                "uid",
                "id",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GroundWaterSubstanceConcentration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "url": obj.get("url"),
                "simulation": obj.get("simulation"),
                "substance": obj.get("substance"),
                "substance_id": obj.get("substance_id"),
                "substance_name": obj.get("substance_name"),
                "initial_concentration": obj.get("initial_concentration"),
                "initial_concentration_id": obj.get("initial_concentration_id"),
                "uid": obj.get("uid"),
                "id": obj.get("id"),
                "aggregation_method": obj.get("aggregation_method"),
            }
        )
        return _obj
