# coding: utf-8

"""
3Di API

3Di simulation API (latest stable version: v3)   Framework release: 3.4.71   3Di core release: 3.6.10  deployed on:  09:22AM (UTC) on September 01, 2025

The version of the OpenAPI document: v3
Contact: info@nelen-schuurmans.nl
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import (
    BaseModel,
    ConfigDict,
    StrictBool,
    StrictInt,
    StrictStr,
    field_validator,
)
from typing_extensions import Self

from ..models.file_read_only import FileReadOnly


class InitialWaterlevel(BaseModel):
    """
    InitialWaterlevel
    """  # noqa: E501

    url: Optional[StrictStr] = None
    threedimodel: Optional[StrictStr] = None
    user_generated: Optional[StrictBool] = None
    file: Optional[FileReadOnly] = None
    source_raster: Optional[StrictStr] = None
    state: Optional[StrictStr] = None
    state_detail: Optional[Dict[str, Any]] = None
    id: Optional[StrictInt] = None
    source_raster_id: Optional[StrictInt] = None
    dimension: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = [
        "url",
        "threedimodel",
        "user_generated",
        "file",
        "source_raster",
        "state",
        "state_detail",
        "id",
        "source_raster_id",
        "dimension",
    ]

    @field_validator("state")
    def state_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["processing", "valid", "invalid"]):
            raise ValueError(
                "must be one of enum values ('processing', 'valid', 'invalid')"
            )
        return value

    @field_validator("dimension")
    def dimension_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["one_d", "two_d"]):
            raise ValueError("must be one of enum values ('one_d', 'two_d')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InitialWaterlevel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set(
            [
                "url",
                "threedimodel",
                "state",
                "state_detail",
                "id",
                "source_raster_id",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of file
        if self.file:
            _dict["file"] = self.file.to_dict()
        # set to None if state_detail (nullable) is None
        # and model_fields_set contains the field
        if self.state_detail is None and "state_detail" in self.model_fields_set:
            _dict["state_detail"] = None

        # set to None if source_raster_id (nullable) is None
        # and model_fields_set contains the field
        if (
            self.source_raster_id is None
            and "source_raster_id" in self.model_fields_set
        ):
            _dict["source_raster_id"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InitialWaterlevel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "url": obj.get("url"),
                "threedimodel": obj.get("threedimodel"),
                "user_generated": obj.get("user_generated"),
                "file": FileReadOnly.from_dict(obj["file"])
                if obj.get("file") is not None
                else None,
                "source_raster": obj.get("source_raster"),
                "state": obj.get("state"),
                "state_detail": obj.get("state_detail"),
                "id": obj.get("id"),
                "source_raster_id": obj.get("source_raster_id"),
                "dimension": obj.get("dimension"),
            }
        )
        return _obj
