# coding: utf-8

"""
3Di API

3Di simulation API (latest stable version: v3)   Framework release: 3.4.71   3Di core release: 3.6.10  deployed on:  09:22AM (UTC) on September 01, 2025

The version of the OpenAPI document: v3
Contact: info@nelen-schuurmans.nl
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional, Set, Union
from uuid import UUID

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictFloat,
    StrictInt,
    StrictStr,
    field_validator,
)
from typing_extensions import Annotated, Self

from ..models.forcing_substance import ForcingSubstance


class LizardRasterRain(BaseModel):
    """
    LizardRasterRain
    """  # noqa: E501

    url: Optional[StrictStr] = None
    uid: Optional[UUID] = None
    offset: Annotated[int, Field(le=2147483647, strict=True, ge=0)] = Field(
        description="offset of event in simulation in seconds"
    )
    duration: Optional[
        Annotated[
            int, Field(le=9223372036854775807, strict=True, ge=-9223372036854775808)
        ]
    ] = Field(
        default=None,
        description="event duration in seconds. -9999 is the 'infinite duration' value (only allowed in conjunction with infinite simulations",
    )
    units: Optional[StrictStr] = None
    reference_uuid: Annotated[str, Field(min_length=1, strict=True, max_length=40)]
    start_datetime: datetime
    simulation: Optional[StrictStr] = None
    multiplier: Optional[Union[StrictFloat, StrictInt]] = None
    interval: Optional[StrictInt] = None
    user: Optional[StrictStr] = None
    user_id: Optional[StrictInt] = None
    origin_offset: Optional[StrictInt] = None
    store_path: Optional[Annotated[str, Field(min_length=1, strict=True)]] = None
    id: Optional[StrictInt] = None
    substances: Optional[List[ForcingSubstance]] = None
    __properties: ClassVar[List[str]] = [
        "url",
        "uid",
        "offset",
        "duration",
        "units",
        "reference_uuid",
        "start_datetime",
        "simulation",
        "multiplier",
        "interval",
        "user",
        "user_id",
        "origin_offset",
        "store_path",
        "id",
        "substances",
    ]

    @field_validator("units")
    def units_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["mm/duration", "mm/h", "m/s"]):
            raise ValueError(
                "must be one of enum values ('mm/duration', 'mm/h', 'm/s')"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LizardRasterRain from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set(
            [
                "url",
                "uid",
                "simulation",
                "interval",
                "user",
                "user_id",
                "origin_offset",
                "store_path",
                "id",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in substances (list)
        _items = []
        if self.substances:
            for _item_substances in self.substances:
                if _item_substances:
                    _items.append(_item_substances.to_dict())
            _dict["substances"] = _items
        # set to None if duration (nullable) is None
        # and model_fields_set contains the field
        if self.duration is None and "duration" in self.model_fields_set:
            _dict["duration"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LizardRasterRain from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "url": obj.get("url"),
                "uid": obj.get("uid"),
                "offset": obj.get("offset"),
                "duration": obj.get("duration"),
                "units": obj.get("units"),
                "reference_uuid": obj.get("reference_uuid"),
                "start_datetime": obj.get("start_datetime"),
                "simulation": obj.get("simulation"),
                "multiplier": obj.get("multiplier"),
                "interval": obj.get("interval"),
                "user": obj.get("user"),
                "user_id": obj.get("user_id"),
                "origin_offset": obj.get("origin_offset"),
                "store_path": obj.get("store_path"),
                "id": obj.get("id"),
                "substances": [
                    ForcingSubstance.from_dict(_item) for _item in obj["substances"]
                ]
                if obj.get("substances") is not None
                else None,
            }
        )
        return _obj
