# coding: utf-8

"""
3Di API

3Di simulation API (latest stable version: v3)   Framework release: 3.4.71   3Di core release: 3.6.10  deployed on:  09:22AM (UTC) on September 01, 2025

The version of the OpenAPI document: v3
Contact: info@nelen-schuurmans.nl
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set, Union
from uuid import UUID

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictFloat,
    StrictInt,
    StrictStr,
    field_validator,
)
from typing_extensions import Annotated, Self

from ..models.forcing_substance_with_zone import ForcingSubstanceWithZone
from ..models.point import Point


class LocalRain(BaseModel):
    """
    LocalRain
    """  # noqa: E501

    url: Optional[StrictStr] = None
    simulation: Optional[StrictStr] = None
    offset: Annotated[int, Field(le=2147483647, strict=True, ge=0)] = Field(
        description="offset of event in simulation in seconds"
    )
    duration: Optional[
        Annotated[
            int, Field(le=9223372036854775807, strict=True, ge=-9223372036854775808)
        ]
    ] = Field(
        default=None,
        description="event duration in seconds. -9999 is the 'infinite duration' value (only allowed in conjunction with infinite simulations",
    )
    interpolate: Optional[StrictBool] = None
    values: Annotated[
        List[
            Annotated[
                List[Union[StrictFloat, StrictInt]], Field(min_length=2, max_length=2)
            ]
        ],
        Field(min_length=1, max_length=300),
    ] = Field(
        description="Timeseries provided as a nested list. The inner list consists of exactly 2 values: timestamp, value"
    )
    units: Optional[StrictStr] = Field(
        default=None, description="m/s is only option for now"
    )
    constant: Optional[StrictBool] = None
    point: Point
    diameter: Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]
    uid: Optional[UUID] = None
    id: Optional[StrictInt] = None
    substances: Optional[List[ForcingSubstanceWithZone]] = None
    __properties: ClassVar[List[str]] = [
        "url",
        "simulation",
        "offset",
        "duration",
        "interpolate",
        "values",
        "units",
        "constant",
        "point",
        "diameter",
        "uid",
        "id",
        "substances",
    ]

    @field_validator("units")
    def units_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["m/s", "mm/h", "mm/min"]):
            raise ValueError("must be one of enum values ('m/s', 'mm/h', 'mm/min')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LocalRain from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set(
            [
                "url",
                "simulation",
                "uid",
                "id",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of point
        if self.point:
            _dict["point"] = self.point.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in substances (list)
        _items = []
        if self.substances:
            for _item_substances in self.substances:
                if _item_substances:
                    _items.append(_item_substances.to_dict())
            _dict["substances"] = _items
        # set to None if duration (nullable) is None
        # and model_fields_set contains the field
        if self.duration is None and "duration" in self.model_fields_set:
            _dict["duration"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LocalRain from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "url": obj.get("url"),
                "simulation": obj.get("simulation"),
                "offset": obj.get("offset"),
                "duration": obj.get("duration"),
                "interpolate": obj.get("interpolate"),
                "values": obj.get("values"),
                "units": obj.get("units"),
                "constant": obj.get("constant"),
                "point": Point.from_dict(obj["point"])
                if obj.get("point") is not None
                else None,
                "diameter": obj.get("diameter"),
                "uid": obj.get("uid"),
                "id": obj.get("id"),
                "substances": [
                    ForcingSubstanceWithZone.from_dict(_item)
                    for _item in obj["substances"]
                ]
                if obj.get("substances") is not None
                else None,
            }
        )
        return _obj
