# coding: utf-8

"""
3Di API

3Di simulation API (latest stable version: v3)   Framework release: 3.4.71   3Di core release: 3.6.10  deployed on:  09:22AM (UTC) on September 01, 2025

The version of the OpenAPI document: v3
Contact: info@nelen-schuurmans.nl
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing_extensions import Annotated, Self


class MeasureLocation(BaseModel):
    """
    MeasureLocation
    """  # noqa: E501

    id: Optional[StrictInt] = None
    weight: StrictStr
    content_type: StrictStr = Field(description="e.g. ")
    content_pk: Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]
    grid_id: Optional[
        Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]
    ] = None
    state: Optional[StrictStr] = None
    state_detail: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = [
        "id",
        "weight",
        "content_type",
        "content_pk",
        "grid_id",
        "state",
        "state_detail",
    ]

    @field_validator("content_type")
    def content_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(
            [
                "v2_connection_node",
                "v2_pipe",
                "v2_orifice",
                "v2_culvert",
                "v2_channel",
                "v2_weir",
            ]
        ):
            raise ValueError(
                "must be one of enum values ('v2_connection_node', 'v2_pipe', 'v2_orifice', 'v2_culvert', 'v2_channel', 'v2_weir')"
            )
        return value

    @field_validator("state")
    def state_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["processing", "valid", "invalid"]):
            raise ValueError(
                "must be one of enum values ('processing', 'valid', 'invalid')"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MeasureLocation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set(
            [
                "id",
                "state",
                "state_detail",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if grid_id (nullable) is None
        # and model_fields_set contains the field
        if self.grid_id is None and "grid_id" in self.model_fields_set:
            _dict["grid_id"] = None

        # set to None if state_detail (nullable) is None
        # and model_fields_set contains the field
        if self.state_detail is None and "state_detail" in self.model_fields_set:
            _dict["state_detail"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MeasureLocation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "weight": obj.get("weight"),
                "content_type": obj.get("content_type"),
                "content_pk": obj.get("content_pk"),
                "grid_id": obj.get("grid_id"),
                "state": obj.get("state"),
                "state_detail": obj.get("state_detail"),
            }
        )
        return _obj
