# coding: utf-8

"""
3Di API

3Di simulation API (latest stable version: v3)   Framework release: 3.4.71   3Di core release: 3.6.10  deployed on:  09:22AM (UTC) on September 01, 2025

The version of the OpenAPI document: v3
Contact: info@nelen-schuurmans.nl
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set, Union
from uuid import UUID

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictFloat,
    StrictInt,
    StrictStr,
    field_validator,
)
from typing_extensions import Annotated, Self

from ..models.linestring import Linestring


class ObstacleEdit(BaseModel):
    """
    ObstacleEdit
    """  # noqa: E501

    url: Optional[StrictStr] = None
    simulation: Optional[StrictStr] = None
    offset: Annotated[int, Field(le=2147483647, strict=True, ge=0)] = Field(
        description="offset of event in simulation in seconds"
    )
    value: Union[StrictFloat, StrictInt] = Field(
        description="Absolute or relative height (in meters)  to use for the linestring"
    )
    linestring: Linestring
    state: Optional[StrictStr] = None
    state_detail: Optional[Dict[str, Any]] = None
    uid: Optional[UUID] = None
    id: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = [
        "url",
        "simulation",
        "offset",
        "value",
        "linestring",
        "state",
        "state_detail",
        "uid",
        "id",
    ]

    @field_validator("state")
    def state_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["processing", "valid", "invalid"]):
            raise ValueError(
                "must be one of enum values ('processing', 'valid', 'invalid')"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ObstacleEdit from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set(
            [
                "url",
                "simulation",
                "state",
                "state_detail",
                "uid",
                "id",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of linestring
        if self.linestring:
            _dict["linestring"] = self.linestring.to_dict()
        # set to None if state_detail (nullable) is None
        # and model_fields_set contains the field
        if self.state_detail is None and "state_detail" in self.model_fields_set:
            _dict["state_detail"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ObstacleEdit from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "url": obj.get("url"),
                "simulation": obj.get("simulation"),
                "offset": obj.get("offset"),
                "value": obj.get("value"),
                "linestring": Linestring.from_dict(obj["linestring"])
                if obj.get("linestring") is not None
                else None,
                "state": obj.get("state"),
                "state_detail": obj.get("state_detail"),
                "uid": obj.get("uid"),
                "id": obj.get("id"),
            }
        )
        return _obj
