# coding: utf-8

"""
3Di API

3Di simulation API (latest stable version: v3)   Framework release: 3.4.71   3Di core release: 3.6.10  deployed on:  09:22AM (UTC) on September 01, 2025

The version of the OpenAPI document: v3
Contact: info@nelen-schuurmans.nl
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set, Union

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictInt,
    StrictStr,
    field_validator,
)
from typing_extensions import Annotated, Self


class OutputSettings(BaseModel):
    """
    OutputSettings
    """  # noqa: E501

    id: Optional[StrictInt] = None
    simulation_id: Optional[StrictInt] = None
    create_hydro_results: Optional[StrictBool] = Field(
        default=None, description="Create domain wide results file."
    )
    create_structure_control_results: Optional[StrictBool] = Field(
        default=None, description="Create structure control results file."
    )
    hydro_output_time_step: Optional[
        Union[
            Annotated[float, Field(strict=True, ge=1e-14)],
            Annotated[int, Field(strict=True, ge=1)],
        ]
    ] = Field(default=None, description="Output time step in seconds.")
    hydro_output_start_time: Optional[
        Union[
            Annotated[float, Field(strict=True, ge=0)],
            Annotated[int, Field(strict=True, ge=0)],
        ]
    ] = Field(default=None, description="Output start time in seconds.")
    hydro_output_end_time: Optional[
        Union[
            Annotated[float, Field(strict=True, ge=1e-14)],
            Annotated[int, Field(strict=True, ge=1)],
        ]
    ] = Field(default=None, description="Output end time in seconds.")
    hydro_output_precision: Optional[StrictInt] = Field(
        default=None, description="Single or double precision output."
    )
    aggregation_output_precision: Optional[StrictInt] = Field(
        default=None,
        description="Single or double precision output for aggregation results.",
    )
    customized_hydro_output_time_step: Optional[
        Union[
            Annotated[float, Field(strict=True, ge=1e-14)],
            Annotated[int, Field(strict=True, ge=1)],
        ]
    ] = Field(default=None, description="Customized hydro output time step in seconds.")
    customized_hydro_output_start_time: Optional[
        Union[
            Annotated[float, Field(strict=True, ge=0)],
            Annotated[int, Field(strict=True, ge=0)],
        ]
    ] = Field(
        default=None, description="Customized hydro output start time in seconds."
    )
    customized_hydro_output_end_time: Optional[
        Union[
            Annotated[float, Field(strict=True, ge=1e-14)],
            Annotated[int, Field(strict=True, ge=1)],
        ]
    ] = Field(default=None, description="Customized hydro output end time in seconds.")
    customized_hydro_output_precision: Optional[StrictInt] = Field(
        default=None,
        description="Single or double precision output for customized hydro results.",
    )
    customized_hydro_output_variables: Optional[List[StrictStr]] = Field(
        default=None,
        description="The output variables for the customized results area.",
    )
    __properties: ClassVar[List[str]] = [
        "id",
        "simulation_id",
        "create_hydro_results",
        "create_structure_control_results",
        "hydro_output_time_step",
        "hydro_output_start_time",
        "hydro_output_end_time",
        "hydro_output_precision",
        "aggregation_output_precision",
        "customized_hydro_output_time_step",
        "customized_hydro_output_start_time",
        "customized_hydro_output_end_time",
        "customized_hydro_output_precision",
        "customized_hydro_output_variables",
    ]

    @field_validator("customized_hydro_output_variables")
    def customized_hydro_output_variables_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(
                [
                    "s1",
                    "vol",
                    "su",
                    "infiltration_rate_simple",
                    "rain",
                    "q_lat",
                    "q_sss",
                    "ucx",
                    "ucy",
                    "leak",
                    "intecepted_volume",
                    "u1",
                    "q",
                    "au",
                    "up1",
                    "qp",
                    "breach_depth",
                    "breach_width",
                    "q_pump",
                ]
            ):
                raise ValueError(
                    "each list item must be one of ('s1', 'vol', 'su', 'infiltration_rate_simple', 'rain', 'q_lat', 'q_sss', 'ucx', 'ucy', 'leak', 'intecepted_volume', 'u1', 'q', 'au', 'up1', 'qp', 'breach_depth', 'breach_width', 'q_pump')"
                )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OutputSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set(
            [
                "id",
                "simulation_id",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if hydro_output_time_step (nullable) is None
        # and model_fields_set contains the field
        if (
            self.hydro_output_time_step is None
            and "hydro_output_time_step" in self.model_fields_set
        ):
            _dict["hydro_output_time_step"] = None

        # set to None if customized_hydro_output_time_step (nullable) is None
        # and model_fields_set contains the field
        if (
            self.customized_hydro_output_time_step is None
            and "customized_hydro_output_time_step" in self.model_fields_set
        ):
            _dict["customized_hydro_output_time_step"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OutputSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "simulation_id": obj.get("simulation_id"),
                "create_hydro_results": obj.get("create_hydro_results"),
                "create_structure_control_results": obj.get(
                    "create_structure_control_results"
                ),
                "hydro_output_time_step": obj.get("hydro_output_time_step"),
                "hydro_output_start_time": obj.get("hydro_output_start_time"),
                "hydro_output_end_time": obj.get("hydro_output_end_time"),
                "hydro_output_precision": obj.get("hydro_output_precision"),
                "aggregation_output_precision": obj.get("aggregation_output_precision"),
                "customized_hydro_output_time_step": obj.get(
                    "customized_hydro_output_time_step"
                ),
                "customized_hydro_output_start_time": obj.get(
                    "customized_hydro_output_start_time"
                ),
                "customized_hydro_output_end_time": obj.get(
                    "customized_hydro_output_end_time"
                ),
                "customized_hydro_output_precision": obj.get(
                    "customized_hydro_output_precision"
                ),
                "customized_hydro_output_variables": obj.get(
                    "customized_hydro_output_variables"
                ),
            }
        )
        return _obj
