# coding: utf-8

"""
3Di API

3Di simulation API (latest stable version: v3)   Framework release: 3.4.71   3Di core release: 3.6.10  deployed on:  09:22AM (UTC) on September 01, 2025

The version of the OpenAPI document: v3
Contact: info@nelen-schuurmans.nl
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set, Union
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing_extensions import Annotated, Self


class Substance(BaseModel):
    """
    Substance
    """  # noqa: E501

    url: Optional[StrictStr] = None
    simulation: Optional[StrictStr] = None
    name: Annotated[str, Field(min_length=1, strict=True, max_length=1024)]
    id: Optional[StrictInt] = None
    diffusion_coefficient: Optional[
        Union[
            Annotated[float, Field(le=1, strict=True, ge=0)],
            Annotated[int, Field(le=1, strict=True, ge=0)],
        ]
    ] = Field(
        default=None, description="The diffusion coefficient (m2/s) for the substance."
    )
    growth_coefficient: Optional[
        Union[
            Annotated[float, Field(strict=True, ge=0)],
            Annotated[int, Field(strict=True, ge=0)],
        ]
    ] = Field(default=None, description="The growth coefficient for the substance.")
    decay_coefficient: Optional[
        Union[
            Annotated[float, Field(strict=True, ge=0)],
            Annotated[int, Field(strict=True, ge=0)],
        ]
    ] = Field(default=None, description="The decay coefficient for the substance.")
    numerical_diffusion_limiter: Optional[StrictInt] = Field(
        default=None,
        description="The numerical diffusion limiter for the substance.   Options:  0 = off 1 = standard ",
    )
    units: Optional[Annotated[str, Field(strict=True, max_length=16)]] = Field(
        default=None, description="The units of the substance."
    )
    uid: Optional[UUID] = None
    __properties: ClassVar[List[str]] = [
        "url",
        "simulation",
        "name",
        "id",
        "diffusion_coefficient",
        "growth_coefficient",
        "decay_coefficient",
        "numerical_diffusion_limiter",
        "units",
        "uid",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Substance from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set(
            [
                "url",
                "simulation",
                "id",
                "uid",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Substance from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "url": obj.get("url"),
                "simulation": obj.get("simulation"),
                "name": obj.get("name"),
                "id": obj.get("id"),
                "diffusion_coefficient": obj.get("diffusion_coefficient"),
                "growth_coefficient": obj.get("growth_coefficient"),
                "decay_coefficient": obj.get("decay_coefficient"),
                "numerical_diffusion_limiter": obj.get("numerical_diffusion_limiter"),
                "units": obj.get("units"),
                "uid": obj.get("uid"),
            }
        )
        return _obj
