# coding: utf-8

"""
3Di API

3Di simulation API (latest stable version: v3)   Framework release: 3.4.71   3Di core release: 3.6.10  deployed on:  09:22AM (UTC) on September 01, 2025

The version of the OpenAPI document: v3
Contact: info@nelen-schuurmans.nl
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set, Union
from uuid import UUID

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictFloat,
    StrictInt,
    StrictStr,
    field_validator,
)
from typing_extensions import Annotated, Self

from ..models.measure_specification import MeasureSpecification


class TableStructureControl(BaseModel):
    """
    TableStructureControl
    """  # noqa: E501

    id: Optional[StrictInt] = None
    url: Optional[StrictStr] = None
    offset: Annotated[int, Field(le=2147483647, strict=True, ge=0)] = Field(
        description="offset of event in simulation in seconds"
    )
    duration: Optional[
        Annotated[
            int, Field(le=9223372036854775807, strict=True, ge=-9223372036854775808)
        ]
    ] = Field(
        description="event duration in seconds. -9999 is the 'infinite duration' value (only allowed in conjunction with infinite simulations"
    )
    measure_specification: MeasureSpecification
    structure_id: Optional[
        Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]
    ] = None
    structure_type: StrictStr
    type: StrictStr
    values: Annotated[
        List[Annotated[List[Union[StrictFloat, StrictInt]], Field(max_length=3)]],
        Field(max_length=150),
    ]
    state: Optional[StrictStr] = None
    state_detail: Optional[Dict[str, Any]] = None
    grid_id: Optional[
        Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]
    ] = None
    uid: Optional[UUID] = None
    __properties: ClassVar[List[str]] = [
        "id",
        "url",
        "offset",
        "duration",
        "measure_specification",
        "structure_id",
        "structure_type",
        "type",
        "values",
        "state",
        "state_detail",
        "grid_id",
        "uid",
    ]

    @field_validator("structure_type")
    def structure_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(
            [
                "v2_pumpstation",
                "v2_pipe",
                "v2_orifice",
                "v2_culvert",
                "v2_weir",
                "v2_channel",
            ]
        ):
            raise ValueError(
                "must be one of enum values ('v2_pumpstation', 'v2_pipe', 'v2_orifice', 'v2_culvert', 'v2_weir', 'v2_channel')"
            )
        return value

    @field_validator("type")
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(
            [
                "set_discharge_coefficients",
                "set_crest_level",
                "set_pump_capacity",
                "set_gate_level",
            ]
        ):
            raise ValueError(
                "must be one of enum values ('set_discharge_coefficients', 'set_crest_level', 'set_pump_capacity', 'set_gate_level')"
            )
        return value

    @field_validator("state")
    def state_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["processing", "valid", "invalid"]):
            raise ValueError(
                "must be one of enum values ('processing', 'valid', 'invalid')"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TableStructureControl from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set(
            [
                "id",
                "url",
                "state",
                "state_detail",
                "uid",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of measure_specification
        if self.measure_specification:
            _dict["measure_specification"] = self.measure_specification.to_dict()
        # set to None if duration (nullable) is None
        # and model_fields_set contains the field
        if self.duration is None and "duration" in self.model_fields_set:
            _dict["duration"] = None

        # set to None if structure_id (nullable) is None
        # and model_fields_set contains the field
        if self.structure_id is None and "structure_id" in self.model_fields_set:
            _dict["structure_id"] = None

        # set to None if state_detail (nullable) is None
        # and model_fields_set contains the field
        if self.state_detail is None and "state_detail" in self.model_fields_set:
            _dict["state_detail"] = None

        # set to None if grid_id (nullable) is None
        # and model_fields_set contains the field
        if self.grid_id is None and "grid_id" in self.model_fields_set:
            _dict["grid_id"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TableStructureControl from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "url": obj.get("url"),
                "offset": obj.get("offset"),
                "duration": obj.get("duration"),
                "measure_specification": MeasureSpecification.from_dict(
                    obj["measure_specification"]
                )
                if obj.get("measure_specification") is not None
                else None,
                "structure_id": obj.get("structure_id"),
                "structure_type": obj.get("structure_type"),
                "type": obj.get("type"),
                "values": obj.get("values"),
                "state": obj.get("state"),
                "state_detail": obj.get("state_detail"),
                "grid_id": obj.get("grid_id"),
                "uid": obj.get("uid"),
            }
        )
        return _obj
