# coding: utf-8

"""
3Di API

3Di simulation API (latest stable version: v3)   Framework release: 3.4.71   3Di core release: 3.6.10  deployed on:  09:22AM (UTC) on September 01, 2025

The version of the OpenAPI document: v3
Contact: info@nelen-schuurmans.nl
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional, Set, Union

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictFloat,
    StrictInt,
    StrictStr,
    field_validator,
)
from typing_extensions import Annotated, Self


class ThreediModelSavedState(BaseModel):
    """
    ThreediModelSavedState
    """  # noqa: E501

    id: Optional[StrictInt] = None
    url: Optional[StrictStr] = None
    name: Annotated[str, Field(min_length=1, strict=True, max_length=80)]
    created: Optional[datetime] = None
    type: StrictStr
    tags: Optional[List[StrictStr]] = Field(
        default=None, description="tags provided as a list of strings"
    )
    used_in_simulation: Optional[StrictStr] = None
    expiry: Optional[datetime] = None
    time: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = Field(
        default=None, description="Time in simulation to create savedstate"
    )
    variables: Optional[Annotated[List[StrictStr], Field(max_length=2)]] = None
    thresholds: Optional[
        Annotated[List[Union[StrictFloat, StrictInt]], Field(max_length=2)]
    ] = None
    __properties: ClassVar[List[str]] = [
        "id",
        "url",
        "name",
        "created",
        "type",
        "tags",
        "used_in_simulation",
        "expiry",
        "time",
        "variables",
        "thresholds",
    ]

    @field_validator("type")
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(["stable_threshold", "timed"]):
            raise ValueError("must be one of enum values ('stable_threshold', 'timed')")
        return value

    @field_validator("variables")
    def variables_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(["s1", "u1"]):
                raise ValueError("each list item must be one of ('s1', 'u1')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ThreediModelSavedState from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set(
            [
                "id",
                "url",
                "used_in_simulation",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if created (nullable) is None
        # and model_fields_set contains the field
        if self.created is None and "created" in self.model_fields_set:
            _dict["created"] = None

        # set to None if expiry (nullable) is None
        # and model_fields_set contains the field
        if self.expiry is None and "expiry" in self.model_fields_set:
            _dict["expiry"] = None

        # set to None if time (nullable) is None
        # and model_fields_set contains the field
        if self.time is None and "time" in self.model_fields_set:
            _dict["time"] = None

        # set to None if variables (nullable) is None
        # and model_fields_set contains the field
        if self.variables is None and "variables" in self.model_fields_set:
            _dict["variables"] = None

        # set to None if thresholds (nullable) is None
        # and model_fields_set contains the field
        if self.thresholds is None and "thresholds" in self.model_fields_set:
            _dict["thresholds"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ThreediModelSavedState from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "url": obj.get("url"),
                "name": obj.get("name"),
                "created": obj.get("created"),
                "type": obj.get("type"),
                "tags": obj.get("tags"),
                "used_in_simulation": obj.get("used_in_simulation"),
                "expiry": obj.get("expiry"),
                "time": obj.get("time"),
                "variables": obj.get("variables"),
                "thresholds": obj.get("thresholds"),
            }
        )
        return _obj
