# coding: utf-8

"""
3Di API

3Di simulation API (latest stable version: v3)   Framework release: 3.4.71   3Di core release: 3.6.10  deployed on:  09:22AM (UTC) on September 01, 2025

The version of the OpenAPI document: v3
Contact: info@nelen-schuurmans.nl
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing_extensions import Annotated, Self


class UserTokens(BaseModel):
    """
    UserTokens
    """  # noqa: E501

    user: StrictInt
    external_user_id: Annotated[
        str, Field(min_length=1, strict=True, max_length=255)
    ] = Field(
        description="The user ID in the external identity provider, which is present as the 'sub' field in tokens."
    )
    created: Optional[datetime] = None
    last_modified: Optional[datetime] = Field(
        default=None, description="The last time this remote user logged in."
    )
    id_token: Optional[StrictStr] = Field(
        default=None,
        description="The most recent ID token provided by the external identity provider.",
    )
    access_token: Optional[StrictStr] = Field(
        default=None,
        description="The most recent access token provided by the external identity provider.",
    )
    refresh_token: Optional[StrictStr] = Field(
        default=None,
        description="The most recent refresh token provided by the external identity provider.",
    )
    __properties: ClassVar[List[str]] = [
        "user",
        "external_user_id",
        "created",
        "last_modified",
        "id_token",
        "access_token",
        "refresh_token",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserTokens from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set(
            [
                "created",
                "last_modified",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserTokens from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "user": obj.get("user"),
                "external_user_id": obj.get("external_user_id"),
                "created": obj.get("created"),
                "last_modified": obj.get("last_modified"),
                "id_token": obj.get("id_token"),
                "access_token": obj.get("access_token"),
                "refresh_token": obj.get("refresh_token"),
            }
        )
        return _obj
