# coding: utf-8

"""
3Di API

3Di simulation API (latest stable version: v3)   Framework release: 3.4.71   3Di core release: 3.6.10  deployed on:  09:22AM (UTC) on September 01, 2025

The version of the OpenAPI document: v3
Contact: info@nelen-schuurmans.nl
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set, Union

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing_extensions import Annotated, Self

from ..models.linestring import Linestring


class WaterLevelProfileRequest(BaseModel):
    """
    WaterLevelProfileRequest
    """  # noqa: E501

    geometry: Linestring
    points_limit: Optional[Annotated[int, Field(le=200, strict=True, ge=1)]] = Field(
        default=None, description="Maximum number of points to return"
    )
    subscribe: StrictBool = Field(
        description="Subscribe for new results during simulation"
    )
    subscribe_rate_limit: Optional[
        Union[
            Annotated[float, Field(le=1, strict=True, ge=0.25)],
            Annotated[int, Field(le=1, strict=True, ge=1)],
        ]
    ] = Field(
        default=None, description="Max number of items per second for subscription"
    )
    __properties: ClassVar[List[str]] = [
        "geometry",
        "points_limit",
        "subscribe",
        "subscribe_rate_limit",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WaterLevelProfileRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of geometry
        if self.geometry:
            _dict["geometry"] = self.geometry.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WaterLevelProfileRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "geometry": Linestring.from_dict(obj["geometry"])
                if obj.get("geometry") is not None
                else None,
                "points_limit": obj.get("points_limit"),
                "subscribe": obj.get("subscribe"),
                "subscribe_rate_limit": obj.get("subscribe_rate_limit"),
            }
        )
        return _obj
